// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: sparkplug_b.proto

package spbproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataType int32

const (
	DataType_DATA_TYPE_UNKNOWN DataType = 0
	DataType_DATA_TYPE_INT32   DataType = 1
	DataType_DATA_TYPE_INT64   DataType = 2
	DataType_DATA_TYPE_FLOAT   DataType = 3
	DataType_DATA_TYPE_DOUBLE  DataType = 4
	DataType_DATA_TYPE_STRING  DataType = 5
	DataType_DATA_TYPE_BOOLEAN DataType = 6
	DataType_DATA_TYPE_BYTES   DataType = 7
)

// Enum value maps for DataType.
var (
	DataType_name = map[int32]string{
		0: "DATA_TYPE_UNKNOWN",
		1: "DATA_TYPE_INT32",
		2: "DATA_TYPE_INT64",
		3: "DATA_TYPE_FLOAT",
		4: "DATA_TYPE_DOUBLE",
		5: "DATA_TYPE_STRING",
		6: "DATA_TYPE_BOOLEAN",
		7: "DATA_TYPE_BYTES",
	}
	DataType_value = map[string]int32{
		"DATA_TYPE_UNKNOWN": 0,
		"DATA_TYPE_INT32":   1,
		"DATA_TYPE_INT64":   2,
		"DATA_TYPE_FLOAT":   3,
		"DATA_TYPE_DOUBLE":  4,
		"DATA_TYPE_STRING":  5,
		"DATA_TYPE_BOOLEAN": 6,
		"DATA_TYPE_BYTES":   7,
	}
)

func (x DataType) Enum() *DataType {
	p := new(DataType)
	*p = x
	return p
}

func (x DataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataType) Descriptor() protoreflect.EnumDescriptor {
	return file_sparkplug_b_proto_enumTypes[0].Descriptor()
}

func (DataType) Type() protoreflect.EnumType {
	return &file_sparkplug_b_proto_enumTypes[0]
}

func (x DataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *DataType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = DataType(num)
	return nil
}

// Deprecated: Use DataType.Descriptor instead.
func (DataType) EnumDescriptor() ([]byte, []int) {
	return file_sparkplug_b_proto_rawDescGZIP(), []int{0}
}

type Metric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Datatype      *DataType              `protobuf:"varint,2,opt,name=datatype,enum=sparkplug.DataType" json:"datatype,omitempty"`
	StringValue   *string                `protobuf:"bytes,3,opt,name=string_value,json=stringValue" json:"string_value,omitempty"`
	IntValue      *int64                 `protobuf:"varint,4,opt,name=int_value,json=intValue" json:"int_value,omitempty"`
	DoubleValue   *float64               `protobuf:"fixed64,5,opt,name=double_value,json=doubleValue" json:"double_value,omitempty"`
	BoolValue     *bool                  `protobuf:"varint,6,opt,name=bool_value,json=boolValue" json:"bool_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_sparkplug_b_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_sparkplug_b_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_sparkplug_b_proto_rawDescGZIP(), []int{0}
}

func (x *Metric) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Metric) GetDatatype() DataType {
	if x != nil && x.Datatype != nil {
		return *x.Datatype
	}
	return DataType_DATA_TYPE_UNKNOWN
}

func (x *Metric) GetStringValue() string {
	if x != nil && x.StringValue != nil {
		return *x.StringValue
	}
	return ""
}

func (x *Metric) GetIntValue() int64 {
	if x != nil && x.IntValue != nil {
		return *x.IntValue
	}
	return 0
}

func (x *Metric) GetDoubleValue() float64 {
	if x != nil && x.DoubleValue != nil {
		return *x.DoubleValue
	}
	return 0
}

func (x *Metric) GetBoolValue() bool {
	if x != nil && x.BoolValue != nil {
		return *x.BoolValue
	}
	return false
}

type Payload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *uint64                `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	Metrics       []*Metric              `protobuf:"bytes,2,rep,name=metrics" json:"metrics,omitempty"`
	Seq           *uint64                `protobuf:"varint,3,opt,name=seq" json:"seq,omitempty"`
	Uuid          *string                `protobuf:"bytes,4,opt,name=uuid" json:"uuid,omitempty"`
	Body          []byte                 `protobuf:"bytes,5,opt,name=body" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payload) Reset() {
	*x = Payload{}
	mi := &file_sparkplug_b_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payload) ProtoMessage() {}

func (x *Payload) ProtoReflect() protoreflect.Message {
	mi := &file_sparkplug_b_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payload.ProtoReflect.Descriptor instead.
func (*Payload) Descriptor() ([]byte, []int) {
	return file_sparkplug_b_proto_rawDescGZIP(), []int{1}
}

func (x *Payload) GetTimestamp() uint64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

func (x *Payload) GetMetrics() []*Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *Payload) GetSeq() uint64 {
	if x != nil && x.Seq != nil {
		return *x.Seq
	}
	return 0
}

func (x *Payload) GetUuid() string {
	if x != nil && x.Uuid != nil {
		return *x.Uuid
	}
	return ""
}

func (x *Payload) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

var File_sparkplug_b_proto protoreflect.FileDescriptor

const file_sparkplug_b_proto_rawDesc = "" +
	"\n" +
	"\x11sparkplug_b.proto\x12\tsparkplug\"\xcf\x01\n" +
	"\x06Metric\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12/\n" +
	"\bdatatype\x18\x02 \x01(\x0e2\x13.sparkplug.DataTypeR\bdatatype\x12!\n" +
	"\fstring_value\x18\x03 \x01(\tR\vstringValue\x12\x1b\n" +
	"\tint_value\x18\x04 \x01(\x03R\bintValue\x12!\n" +
	"\fdouble_value\x18\x05 \x01(\x01R\vdoubleValue\x12\x1d\n" +
	"\n" +
	"bool_value\x18\x06 \x01(\bR\tboolValue\"\x8e\x01\n" +
	"\aPayload\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x04R\ttimestamp\x12+\n" +
	"\ametrics\x18\x02 \x03(\v2\x11.sparkplug.MetricR\ametrics\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x04R\x03seq\x12\x12\n" +
	"\x04uuid\x18\x04 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04body\x18\x05 \x01(\fR\x04body*\xb8\x01\n" +
	"\bDataType\x12\x15\n" +
	"\x11DATA_TYPE_UNKNOWN\x10\x00\x12\x13\n" +
	"\x0fDATA_TYPE_INT32\x10\x01\x12\x13\n" +
	"\x0fDATA_TYPE_INT64\x10\x02\x12\x13\n" +
	"\x0fDATA_TYPE_FLOAT\x10\x03\x12\x14\n" +
	"\x10DATA_TYPE_DOUBLE\x10\x04\x12\x14\n" +
	"\x10DATA_TYPE_STRING\x10\x05\x12\x15\n" +
	"\x11DATA_TYPE_BOOLEAN\x10\x06\x12\x13\n" +
	"\x0fDATA_TYPE_BYTES\x10\aB#Z!sparkbridge/pkg/spbproto;spbproto"

var (
	file_sparkplug_b_proto_rawDescOnce sync.Once
	file_sparkplug_b_proto_rawDescData []byte
)

func file_sparkplug_b_proto_rawDescGZIP() []byte {
	file_sparkplug_b_proto_rawDescOnce.Do(func() {
		file_sparkplug_b_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sparkplug_b_proto_rawDesc), len(file_sparkplug_b_proto_rawDesc)))
	})
	return file_sparkplug_b_proto_rawDescData
}

var file_sparkplug_b_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sparkplug_b_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sparkplug_b_proto_goTypes = []any{
	(DataType)(0),   // 0: sparkplug.DataType
	(*Metric)(nil),  // 1: sparkplug.Metric
	(*Payload)(nil), // 2: sparkplug.Payload
}
var file_sparkplug_b_proto_depIdxs = []int32{
	0, // 0: sparkplug.Metric.datatype:type_name -> sparkplug.DataType
	1, // 1: sparkplug.Payload.metrics:type_name -> sparkplug.Metric
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_sparkplug_b_proto_init() }
func file_sparkplug_b_proto_init() {
	if File_sparkplug_b_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sparkplug_b_proto_rawDesc), len(file_sparkplug_b_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sparkplug_b_proto_goTypes,
		DependencyIndexes: file_sparkplug_b_proto_depIdxs,
		EnumInfos:         file_sparkplug_b_proto_enumTypes,
		MessageInfos:      file_sparkplug_b_proto_msgTypes,
	}.Build()
	File_sparkplug_b_proto = out.File
	file_sparkplug_b_proto_goTypes = nil
	file_sparkplug_b_proto_depIdxs = nil
}
