mqtt:
  broker_url: "tcps://cloud-broker.example.com:8883"
  client_id: ""
  keep_alive_sec: 30

sparkplug:
  group_id: ""
  node_id: ""
  namespace: "spBv1.0"

grpc_server:
  socket_path: "/var/run/parkline/spb.sock"  # Или TCP порт 0.0.0.0:50051
