syntax = "proto3";

package sparkplug.v1;

option go_package = "sparkplugb-agent/pkg/pb;pb";

service SparkplugIngressService {
  rpc Bridge (stream EdgeMessage) returns (stream CloudCommand);
}

message EdgeMessage {
  string client_id = 1;
  string device_id = 2;
  repeated Metric metrics = 3;
}

message Metric {
  string name = 1;
  int64 timestamp = 2;
  oneof value {
    int64 int_value = 3;
    double double_value = 4;
    string string_value = 5;
    bool bool_value = 6;
  }
}

message CloudCommand {
  string client_id = 1;
  string command_id = 2;
  string target_device = 3;
  string action = 4;
  map<string, string> parameters = 5;
}
